#!/usr/bin/env python3
"""
Generate the English static variant (<page>.en.html) of every page that carries the inline
i18n engine, so nginx can answer an English visitor with English HTML on the very first
byte (deploy/nginx/shell.fans.conf: `map $cookie_shellfans_locale $sf_lang`).

Why a build step and not a runtime swap
---------------------------------------
shell.fans is a static site. Until 2026-09-13 the served HTML was always zh-TW and the
page's own JavaScript replaced every `[data-i18n]` element after DOMContentLoaded when
localStorage said `en` — visitors saw Chinese for a frame (or seconds on slow networks).
The server cannot read localStorage, so the only way to render the right language before
the first paint is to (a) persist the preference in a cookie and (b) already have the
English HTML to serve. This script produces (b) by applying the page's OWN dictionary
(`BASE.en` inside the inline engine) with the SAME semantics as the runtime
`applyTranslations()`:

  data-i18n + data-i18n-attr="x"  → attribute x        (runtime: el.setAttribute)
  data-i18n + data-i18n-html      → inner HTML         (runtime: el.innerHTML)
  data-i18n                       → text, HTML-escaped (runtime: el.textContent)
  missing key                     → zh-TW value, then the key itself (runtime `resolve`)

plus what the runtime meta script does (`<title>`, description, og:title/description) and
the parts the runtime never touches but a first render must get right: `<html lang>`,
og:locale (+alternate), twitter:title/description, the language-switcher check marks and
the crawlable footer baked inside `#sf-footer-root` (translated with the localized strings
of js/sf-footer.js SHELL_BASE, keeping the `data-sf-product` markers the Cloudflare
Worker relies on).

The generated page keeps the engine and both dictionaries, so switching back to zh-TW on
the client still works without a reload, and it keeps every `<a href>` the zh page has.

Usage
-----
  python3 scripts/build-locale-pages.py            # (re)generate all *.en.html
  python3 scripts/build-locale-pages.py --check    # exit 1 if any variant is missing/stale

Run it after ANY change to an engine page or to js/sf-footer.js SHELL_BASE. Node.js is
used only to evaluate the dictionary object literals (they are JavaScript, not JSON).
"""

from __future__ import annotations

import html
import json
import re
import subprocess
import sys
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENGINE_MARK = 'window.__setLocale = function'
# The navigation between these markers is owned by scripts/apply-global-ui-nav.py, which bakes the
# *published* Global UI nav per locale (data-i18n stripped so the page i18n engine never overwrites it).
# This generator must stay agnostic to that block: the zh source carries zh labels, the en variant en
# labels, so we adopt whatever apply-global-ui-nav.py already baked into the target instead of copying
# the zh block across. Pipeline: run build-locale-pages.py first, then apply-global-ui-nav.py on both
# <page>.html and <page>.en.html.
NAV_MARK_OPEN = '<!--sf-gui-nav:start-->'
NAV_MARK_CLOSE = '<!--sf-gui-nav:end-->'
NAV_BLOCK_RE = re.compile(re.escape(NAV_MARK_OPEN) + r'.*?' + re.escape(NAV_MARK_CLOSE), re.S)
VOID = {'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta',
        'param', 'source', 'track', 'wbr'}
BANNER = ('<!-- Generated by scripts/build-locale-pages.py from {src} — DO NOT EDIT. '
          'Served by nginx when cookie shellfans_locale=en. Regenerate instead. -->')

# UI strings that live in js/sf-footer.js build() rather than in SHELL_BASE.
FOOTER_UI = {
    '網站導覽': 'Site navigation',
    '公司資訊': 'Company info',
    '社群連結': 'Social links',
    '切換語言': 'Switch language',
}


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def node_eval_object(js_object_literal: str) -> dict:
    """Evaluate a JS object literal with Node and return it as a Python dict."""
    proc = subprocess.run(
        ['node', '-e',
         "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{"
         "const o=new Function('return '+s)();process.stdout.write(JSON.stringify(o))})"],
        input=js_object_literal.encode('utf-8'), capture_output=True, check=True)
    return json.loads(proc.stdout.decode('utf-8'))


def extract_base(page_html: str) -> dict:
    anchor = page_html.find("var STORAGE_KEY = 'shellfans_locale';")
    if anchor < 0:
        raise ValueError('inline i18n engine not found')
    i = page_html.find('var BASE = {', anchor)
    j = page_html.find('\n  };', i)
    if i < 0 or j < 0:
        raise ValueError('BASE dictionary not found')
    return node_eval_object(page_html[i + len('var BASE = '):j + 4])


def extract_footer_base() -> dict:
    js = (ROOT / 'js' / 'sf-footer.js').read_text(encoding='utf-8')
    i = js.find('var SHELL_BASE = {')
    j = js.find('\n  };', i)
    if i < 0 or j < 0:
        raise ValueError('SHELL_BASE not found in js/sf-footer.js')
    return node_eval_object(js[i + len('var SHELL_BASE = '):j + 4])


def attr_escape(v: str) -> str:
    return v.replace('&', '&amp;').replace('"', '&quot;').replace('<', '&lt;').replace('>', '&gt;')


def set_attr(start_tag: str, name: str, value: str) -> str:
    """Return the raw start tag with attribute `name` set to `value` (added if absent)."""
    pat = re.compile(r'(\s%s=")([^"]*)(")' % re.escape(name))
    if pat.search(start_tag):
        return pat.sub(lambda m: m.group(1) + attr_escape(value) + m.group(3), start_tag, count=1)
    close = '/>' if start_tag.endswith('/>') else '>'
    return start_tag[:-len(close)].rstrip() + f' {name}="{attr_escape(value)}"' + close


class I18nScanner(HTMLParser):
    """Position-aware scan of every element carrying data-i18n."""

    def __init__(self, text: str):
        super().__init__(convert_charrefs=False)
        self.text = text
        self.line_starts = [0]
        for m in re.finditer('\n', text):
            self.line_starts.append(m.end())
        self.stack: list[tuple[str, dict | None]] = []
        self.elems: list[dict] = []

    def abs_pos(self) -> int:
        line, col = self.getpos()
        return self.line_starts[line - 1] + col

    def handle_starttag(self, tag, attrs):
        raw = self.get_starttag_text() or ''
        start = self.abs_pos()
        a = dict(attrs)
        elem = None
        if 'data-i18n' in a:
            elem = {'tag': tag, 'start': start, 'start_end': start + len(raw), 'raw': raw,
                    'key': a.get('data-i18n') or '', 'attr': a.get('data-i18n-attr'),
                    'is_html': 'data-i18n-html' in a, 'inner_start': start + len(raw),
                    'inner_end': None}
            self.elems.append(elem)
        if tag not in VOID and not raw.endswith('/>'):
            self.stack.append((tag, elem))

    def handle_startendtag(self, tag, attrs):
        # <img ... /> style: void, attribute-only
        raw = self.get_starttag_text() or ''
        start = self.abs_pos()
        a = dict(attrs)
        if 'data-i18n' in a:
            self.elems.append({'tag': tag, 'start': start, 'start_end': start + len(raw), 'raw': raw,
                               'key': a.get('data-i18n') or '', 'attr': a.get('data-i18n-attr'),
                               'is_html': 'data-i18n-html' in a, 'inner_start': None, 'inner_end': None})

    def handle_endtag(self, tag):
        pos = self.abs_pos()
        for k in range(len(self.stack) - 1, -1, -1):
            if self.stack[k][0] == tag:
                elem = self.stack[k][1]
                if elem is not None:
                    elem['inner_end'] = pos
                del self.stack[k:]
                return


def resolve(key: str, base: dict) -> str:
    en = base.get('en', {})
    zh = base.get('zh-TW', {})
    return en.get(key) or zh.get(key) or key


def translate_footer(fragment: str, fb: dict) -> str:
    """Translate the crawlable zh-TW footer baked in #sf-footer-root into English."""
    mapping: dict[str, str] = dict(FOOTER_UI)

    def add(ls):
        if isinstance(ls, dict) and ls.get('zh-TW') and ls.get('en'):
            mapping[ls['zh-TW']] = ls['en']

    add(fb.get('description'))
    for g in fb.get('linkGroups', []):
        add(g.get('title'))
        for lk in g.get('links', []):
            add(lk.get('label'))
    for ln in fb.get('company', {}).get('lines', []):
        add(ln.get('text'))
    p = fb.get('patent', {})
    add(p.get('before')); add(p.get('linkText')); add(p.get('after'))
    add(fb.get('copyright', {}).get('text'))
    for lk in fb.get('legal', []):
        add(lk.get('label'))

    def repl_text(m):
        inner = m.group(1)
        key = inner.strip()
        if key in mapping:
            return '>' + inner.replace(key, mapping[key]) + '<'
        if key == 'English':                # the toggle shows the OTHER language
            return '>' + inner.replace('English', '繁體中文') + '<'
        return m.group(0)

    out = re.sub(r'>([^<]+)<', repl_text, fragment)
    for zh, en in mapping.items():
        out = out.replace(f'aria-label="{zh}"', f'aria-label="{en}"')
    for zh, en in FOOTER_UI.items():
        out = out.replace(f'aria-label="{zh}"', f'aria-label="{en}"')
    logo = fb.get('logo', {})
    src = logo.get('src', {}); alt = logo.get('alt', {})
    if isinstance(src, dict) and src.get('zh-TW') and src.get('en'):
        out = out.replace(f'src="{src["zh-TW"]}"', f'src="{src["en"]}"', 1)
    if isinstance(alt, dict) and alt.get('zh-TW') and alt.get('en'):
        out = out.replace(f'alt="{alt["zh-TW"]}"', f'alt="{alt["en"]}"', 1)
    return out


def graft_nav_blocks(variant: str, existing: str) -> str:
    """Replace the baked-nav blocks in `variant` (copied verbatim from the zh source, so still zh)
    with the per-locale blocks apply-global-ui-nav.py already baked into `existing` (the target
    .en.html). Positional, in document order — both files share the same containers in the same order.
    If the target has no baked nav yet, or the block counts differ (structure drift), leave `variant`
    untouched and let apply-global-ui-nav.py reconcile it; never corrupt the block."""
    ex_blocks = NAV_BLOCK_RE.findall(existing)
    if not ex_blocks:
        return variant
    if len(NAV_BLOCK_RE.findall(variant)) != len(ex_blocks):
        return variant
    it = iter(ex_blocks)
    return NAV_BLOCK_RE.sub(lambda m: next(it), variant)


def build_variant(src_rel: str, page_html: str, base: dict, footer_base: dict) -> str:
    scanner = I18nScanner(page_html)
    scanner.feed(page_html)
    scanner.close()

    repl: list[tuple[int, int, str]] = []
    for e in scanner.elems:
        val = resolve(e['key'], base)
        if e['attr']:
            repl.append((e['start'], e['start_end'], set_attr(e['raw'], e['attr'], val)))
        elif e['inner_start'] is None or e['inner_end'] is None:
            raise ValueError(f'{src_rel}: unclosed data-i18n element {e["tag"]} key={e["key"]}')
        elif e['is_html']:
            repl.append((e['inner_start'], e['inner_end'], val))
        else:
            repl.append((e['inner_start'], e['inner_end'], html.escape(val, quote=False)))

    out = page_html
    for start, end, new in sorted(repl, key=lambda r: r[0], reverse=True):
        out = out[:start] + new + out[end:]

    # ---- document language + metadata (what the runtime meta script does, plus og/twitter)
    out, n = re.subn(r'<html lang="zh-Hant">', '<html lang="en">', out, count=1)
    if n != 1:
        raise ValueError(f'{src_rel}: <html lang="zh-Hant"> not found')
    out = out.replace('<meta property="og:locale:alternate" content="en_US">',
                      '<meta property="og:locale:alternate" content="zh_TW">', 1)
    out = out.replace('<meta property="og:locale" content="zh_TW">',
                      '<meta property="og:locale" content="en_US">', 1)
    en = base.get('en', {})
    title = en.get('meta.title')
    desc = en.get('meta.description')
    head_end = out.find('</head>')
    head, body = out[:head_end], out[head_end:]
    if title:
        head = re.sub(r'<title>[^<]*</title>', '<title>' + html.escape(title, quote=False) + '</title>', head, count=1)
        for sel in ('property="og:title"', 'name="twitter:title"'):
            head = re.sub(r'(<meta %s content=")[^"]*(")' % re.escape(sel),
                          lambda m: m.group(1) + attr_escape(title) + m.group(2), head, count=1)
    if desc:
        for sel in ('name="description"', 'property="og:description"', 'name="twitter:description"'):
            head = re.sub(r'(<meta %s content=")[^"]*(")' % re.escape(sel),
                          lambda m: m.group(1) + attr_escape(desc) + m.group(2), head, count=1)
    out = head + body

    # ---- language switcher check marks: English is the active entry now
    def check_state(m):
        tag = m.group(0)
        which = m.group(1)
        if which == 'zh-TW' and 'display:none' not in tag:
            tag = re.sub(r'style="([^"]*)"', lambda s: 'style="' + s.group(1).rstrip(';') + ';display:none"', tag, count=1)
        elif which == 'en':
            tag = tag.replace(';display:none', '').replace('display:none;', '').replace('display:none', '')
        return tag
    out = re.sub(r'<svg[^>]*data-check-for="(zh-TW|en)"[^>]*>', check_state, out)

    # ---- crawlable footer baseline
    fs = out.find('<div id="sf-footer-root">')
    fe = out.find('</footer>', fs)
    if fs >= 0 and fe >= 0:
        out = out[:fs] + translate_footer(out[fs:fe], footer_base) + out[fe:]

    # ---- banner right after the doctype
    out = re.sub(r'^(<!DOCTYPE html>\s*\n)', lambda m: m.group(1) + BANNER.format(src=src_rel) + '\n', out, count=1, flags=re.I)
    return out


def verify_variant(src_rel: str, variant: str, base: dict) -> list[str]:
    """Re-scan the output and prove every data-i18n element carries its English value."""
    problems: list[str] = []
    scanner = I18nScanner(variant)
    scanner.feed(variant)
    scanner.close()
    for e in scanner.elems:
        want = resolve(e['key'], base)
        if e['attr']:
            m = re.search(r'\s%s="([^"]*)"' % re.escape(e['attr']), e['raw'])
            got = html.unescape(m.group(1)) if m else None
        elif e['is_html']:
            got = variant[e['inner_start']:e['inner_end']]
        else:
            got = html.unescape(variant[e['inner_start']:e['inner_end']])
        if got != want:
            problems.append(f'{src_rel}: key {e["key"]} ({e["tag"]}) = {got!r:.60} != {want!r:.60}')
    if '<html lang="en">' not in variant:
        problems.append(f'{src_rel}: html lang is not en')
    if '<html lang="zh-Hant">' in variant:
        problems.append(f'{src_rel}: zh-Hant lang left behind')
    title = base.get('en', {}).get('meta.title')
    if title and f'<title>{html.escape(title, quote=False)}</title>' not in variant:
        problems.append(f'{src_rel}: <title> is not the English meta.title')
    if variant.count('<a href=') != 0 and variant.count('<a href=') < 5:
        problems.append(f'{src_rel}: suspiciously few <a href> links')
    return problems


def engine_pages() -> list[Path]:
    pages = []
    for p in sorted(ROOT.rglob('*.html')):
        parts = p.relative_to(ROOT).parts
        if any(x in ('docs', 'node_modules', '.git', 'partials', 'deploy') for x in parts):
            continue
        if p.name.endswith('.en.html'):
            continue
        if ENGINE_MARK in p.read_text(encoding='utf-8'):
            pages.append(p)
    return pages


def main(argv: list[str]) -> int:
    check = '--check' in argv
    footer_base = extract_footer_base()
    bad = 0
    for p in engine_pages():
        rel = str(p.relative_to(ROOT))
        target = p.with_name(p.name[:-len('.html')] + '.en.html')
        page_html = p.read_text(encoding='utf-8')
        base = extract_base(page_html)
        variant = build_variant(rel, page_html, base, footer_base)
        if target.exists():
            variant = graft_nav_blocks(variant, target.read_text(encoding='utf-8'))
        problems = verify_variant(rel, variant, base)
        if problems:
            bad += 1
            print(f'{rel}: VERIFY FAILED')
            for x in problems[:10]:
                print('   ', x)
            continue
        if check:
            if not target.exists():
                bad += 1; print(f'{target.relative_to(ROOT)}: MISSING')
            elif target.read_text(encoding='utf-8') != variant:
                bad += 1; print(f'{target.relative_to(ROOT)}: STALE (regenerate)')
            else:
                print(f'{target.relative_to(ROOT)}: OK')
        else:
            changed = (not target.exists()) or target.read_text(encoding='utf-8') != variant
            target.write_text(variant, encoding='utf-8')
            print(f'{target.relative_to(ROOT)}: {"written" if changed else "unchanged"} '
                  f'({len(base.get("en", {}))} en keys, links={variant.count("<a href=")})')
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
